[build]
  base    = "."
  publish = "./src/"
  environment = {NODE_VERSION = "16.16.0" }

# Set enviroment variable prompts for templates
[template.environment]
  VONAGE_API_KEY = "Your Vonage API key"
  VONAGE_API_SECRET = "Your Vonage API secret"
  DAILY_API_KEY = "Your Daily API key"
  USE_DAILY = "TRUE if you want to use Daily instead of Vonage"